/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;
import com.sun.org.apache.bcel.internal.generic.BREAKPOINT;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.ClassicMedia;
import model.quaries;

/**
 *
 * @author Naveen
 */
public class addUser extends javax.swing.JFrame {

    String status;

    /**
     * Creates new form addUser
     */
    public addUser(String getPath) {
        status = JOptionPane.showInputDialog("Enter Status :");
        initComponents();
//        path = getPath;
        if (getPath == "Save") {
            sBtn.setVisible(true);
            uBtn.setVisible(false);
        }
        if (getPath == "Update") {
            uBtn.setVisible(true);
            sBtn.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        uBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtnic = new javax.swing.JTextField();
        ttname = new javax.swing.JTextField();
        jbm = new javax.swing.JRadioButton();
        jbf = new javax.swing.JRadioButton();
        txthome = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        sBtn = new javax.swing.JButton();
        txtmobile1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        uBtn.setText("update");
        uBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uBtnActionPerformed(evt);
            }
        });
        uBtn.setBounds(560, 590, 100, 40);
        jLayeredPane1.add(uBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(320, 540, 51, 23);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtnic.setBackground(new java.awt.Color(247, 247, 247));
        txtnic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnicKeyReleased(evt);
            }
        });
        txtnic.setBounds(320, 190, 360, 30);
        jLayeredPane1.add(txtnic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ttname.setBackground(new java.awt.Color(247, 247, 247));
        ttname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ttname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ttnameKeyTyped(evt);
            }
        });
        ttname.setBounds(320, 230, 370, 30);
        jLayeredPane1.add(ttname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbm.setBackground(new java.awt.Color(247, 247, 247));
        jbm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbm.setForeground(new java.awt.Color(0, 177, 255));
        jbm.setText("Male");
        jbm.setBounds(340, 270, 55, 25);
        jLayeredPane1.add(jbm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbf.setBackground(new java.awt.Color(247, 247, 247));
        jbf.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbf.setForeground(new java.awt.Color(0, 177, 255));
        jbf.setText("Female");
        jbf.setBounds(420, 270, 69, 25);
        jLayeredPane1.add(jbf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txthome.setBackground(new java.awt.Color(247, 247, 247));
        txthome.setText("+94");
        txthome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthomeActionPerformed(evt);
            }
        });
        txthome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthomeKeyTyped(evt);
            }
        });
        txthome.setBounds(320, 410, 170, 30);
        jLayeredPane1.add(txthome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtaddress.setBackground(new java.awt.Color(247, 247, 247));
        txtaddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtaddress.setBounds(320, 450, 360, 30);
        jLayeredPane1.add(txtaddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        image.setBounds(0, 0, 270, 260);
        jDesktopPane1.add(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setBounds(820, 200, 270, 260);
        jLayeredPane1.add(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Attach");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(880, 500, 130, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sBtn.setText("Save");
        sBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBtnActionPerformed(evt);
            }
        });
        sBtn.setBounds(690, 590, 110, 40);
        jLayeredPane1.add(sBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtmobile1.setBackground(new java.awt.Color(247, 247, 247));
        txtmobile1.setText("+94");
        txtmobile1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmobile1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmobile1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmobile1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobile1KeyTyped(evt);
            }
        });
        txtmobile1.setBounds(320, 370, 170, 30);
        jLayeredPane1.add(txtmobile1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user_1.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 1366, 768);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyReleased

        if (txtnic.getCaretPosition() == 9) {
            if (txtnic.getText().lastIndexOf("v") == -1) {
                txtnic.setText(txtnic.getText() + "v");
            }
            evt.consume();

            if (Integer.parseInt(txtnic.getText().substring(2, 5)) > 500) {
                //                if (Integer.parseInt(txtnic.getText().substring(0, 2)) + 1900 > new DateTime().getYear() - 23) {
                jbf.setSelected(true);
                //                }

            } else {
                jbm.setSelected(true);
            }
            if (ttname.getText().isEmpty()) {
            } else {
                if (Character.isLowerCase(ttname.getText().charAt(0))) {
                    ttname.setText(new String(String.valueOf(ttname.getText().charAt(0))).toUpperCase() + ttname.getText().substring(1));
                }
            }
        }
    }//GEN-LAST:event_txtnicKeyReleased

    private void ttnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttnameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) | c == ' ')) {
            evt.consume();

        }
        if (ttname.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_ttnameKeyTyped

    private void txthomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthomeKeyPressed
        // TODO add your handling code here:

        if (txthome.getCaretPosition() <= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txthomeKeyPressed

    private void txthomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthomeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) | c == '+')) {
            evt.consume();
        }
        if (txthome.getText().length() == 12) {
            evt.consume();
        }

        if (txthome.getCaretPosition() == 3) {

            if (evt.getKeyChar() == '0') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txthomeKeyTyped

    private void txthomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthomeKeyReleased
    }//GEN-LAST:event_txthomeKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JFileChooser jf = new JFileChooser();
            jf.showOpenDialog(this);
            File f = jf.getSelectedFile();
            String path = f.getAbsolutePath();
            jpath = path.replace("\\", "/");
            //-----------------------------
            File ff = new File(path);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
            image.setIcon(new ImageIcon(img));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    String m = " ";
    private void sBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnActionPerformed
        try {

            String[] getData = autoGenerate();
            if (jbm.isSelected()) {
                m = "m";
            } else if (jbf.isSelected()) {
                m = "f";

            }
            // String[] name = ttname.getText().split(" ");
            try {

                //----------SMS GENERATE------------------------------------------------
                ClassicMedia.sendSms(txtmobile1.getText(), getData[0] + " Your Verification Code : " + getData[1]);
                String feild[] = {txtnic.getText(), ttname.getText(), m, txtmobile1.getText(), txthome.getText(), txtaddress.getText(), jpath, status};
                String login[] = {getData[0], getData[1], txtnic.getText()};
                quaries.autosave("usertype", feild, login);
                JOptionPane.showMessageDialog(this, "Succesfull !");



                //        String[] ar={"123","123","123","123","123","123","123","123","123","123","123"};
                //        quaries.autosave("usertype", ar);
            } catch (Exception e) {
                e.printStackTrace();
            }



        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e, "SMS", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_sBtnActionPerformed

    private void txtmobile1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobile1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobile1KeyPressed

    private void txtmobile1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobile1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) | c == '+')) {
            evt.consume();
        }
        if (txtmobile1.getText().length() == 12) {
            evt.consume();
        }

        if (txtmobile1.getCaretPosition() == 3) {

            if (evt.getKeyChar() == '0') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtmobile1KeyTyped

    private void txtmobile1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobile1KeyReleased
        if (txtmobile1.getCaretPosition() <= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtmobile1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthomeActionPerformed

    private void uBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uBtnActionPerformed
        try {
            String name[] = {"user_name", "user_gender", "user_mobileNumber", "user_homeNumber", "user_address"};
            String column[] = {ttname.getText(), m, txtmobile1.getText(), txthome.getText(), txtaddress.getText()};

            quaries.update("usertype", name, column, txtnic.getText(), "user_nic");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_uBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addUser add = new addUser("Save");
                AWTUtilities.setWindowOpaque(add, false);
                add.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JRadioButton jbf;
    public javax.swing.JRadioButton jbm;
    private javax.swing.JButton sBtn;
    public javax.swing.JTextField ttname;
    public javax.swing.JTextField txtaddress;
    public javax.swing.JTextField txthome;
    public javax.swing.JTextField txtmobile1;
    public javax.swing.JTextField txtnic;
    private javax.swing.JButton uBtn;
    // End of variables declaration//GEN-END:variables
    String jpath;

    private String[] autoGenerate() {
        String username, password;
        String name, number1, number2;
        String ar[];
        number1 = txtnic.getText().substring(0, 2);
        number2 = txtnic.getText().substring(7, 9);
        if (ttname.getText().contains(" ")) {
            ar = ttname.getText().split(" ");
            username = ar[0] + number1 + number2;
        } else {
            name = ttname.getText();
            username = name + number1 + number2;
        }

        password = new Random().nextInt(800000) + 100000 + "";
        String[] userPass = {username, password};
        return userPass;
    }
//    public void pic()throws Exception{
//        FileInputStream file=new FileInputStream(new File(jpath));
//        int[] i=new int[128];
//        for(int t=0;t<i.length;t++){
//            i[t]=file.read();
//            System.out.println(i);
//        }
//    }
}
