/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;
import control.DBConnection;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class ControlPanel1 extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanel1
     */
    public ControlPanel1(String currentUser) {
        initComponents();
        accUserName = currentUser;
        jLabel7.setText(accUserName);//-----setting userName into UserAccounts homePanel----
        methods();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeUserName = new javax.swing.JLayeredPane();
        txt_userName = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        image1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        changePassword = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        image2 = new javax.swing.JLabel();
        txt_newPas = new javax.swing.JPasswordField();
        txt_confirmPas = new javax.swing.JPasswordField();
        txt_currPas = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        invalidCurPas = new javax.swing.JLabel();
        pdmatch = new javax.swing.JLabel();
        pmatch = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        strong = new javax.swing.JLabel();
        medium = new javax.swing.JLabel();
        small = new javax.swing.JLabel();
        red = new javax.swing.JLabel();
        blue = new javax.swing.JLabel();
        green = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changeAccPic = new javax.swing.JLayeredPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        image3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        userpicChange = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserAccounts = new javax.swing.JLayeredPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ControlPanel = new javax.swing.JLayeredPane();
        deleteOwnAcc = new javax.swing.JLayeredPane();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        txt_userName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_userName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_userName.setBounds(230, 210, 450, 30);
        changeUserName.add(txt_userName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        image1.setBounds(0, 0, 220, 200);
        jDesktopPane2.add(image1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBounds(830, 200, 220, 200);
        changeUserName.add(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/change_user.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(330, 280, 360, 90);
        changeUserName.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/userNameChange.png"))); // NOI18N
        jLabel2.setBounds(0, 0, 1366, 768);
        changeUserName.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setBounds(200, 80, 150, 30);
        changePassword.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        image2.setBounds(0, 0, 220, 200);
        jDesktopPane3.add(image2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(820, 140, 220, 200);
        changePassword.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_newPas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_newPas.setOpaque(false);
        txt_newPas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_newPasKeyReleased(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_newPasKeyPressed(evt);
            }
        });
        txt_newPas.setBounds(240, 295, 410, 30);
        changePassword.add(txt_newPas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_confirmPas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_confirmPas.setOpaque(false);
        txt_confirmPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmPasActionPerformed(evt);
            }
        });
        txt_confirmPas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_confirmPasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_confirmPasKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_confirmPasKeyPressed(evt);
            }
        });
        txt_confirmPas.setBounds(240, 420, 410, 30);
        changePassword.add(txt_confirmPas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_currPas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_currPas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_currPasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_currPasKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_currPasKeyPressed(evt);
            }
        });
        txt_currPas.setBounds(240, 170, 410, 30);
        changePassword.add(txt_currPas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Enter the new password");
        jLabel4.setBounds(240, 240, 430, 30);
        changePassword.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Confirm password");
        jLabel5.setBounds(240, 370, 430, 30);
        changePassword.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Enter the current password");
        jLabel6.setBounds(240, 120, 430, 30);
        changePassword.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        invalidCurPas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        invalidCurPas.setForeground(new java.awt.Color(255, 51, 51));
        invalidCurPas.setText("Invalid Password");
        invalidCurPas.setBounds(530, 210, 130, 30);
        changePassword.add(invalidCurPas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pdmatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pdmatch.setForeground(new java.awt.Color(255, 51, 51));
        pdmatch.setText("Password Did not Matched");
        pdmatch.setBounds(470, 460, 190, 30);
        changePassword.add(pdmatch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pmatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pmatch.setForeground(new java.awt.Color(0, 153, 51));
        pmatch.setText("Password Matched");
        pmatch.setBounds(520, 460, 140, 30);
        changePassword.add(pmatch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/cp.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/cpg.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(300, 520, 380, 100);
        changePassword.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        strong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        strong.setText("Strong ");
        strong.setBounds(590, 330, 70, 30);
        changePassword.add(strong, javax.swing.JLayeredPane.DEFAULT_LAYER);

        medium.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        medium.setText("Medium");
        medium.setBounds(590, 330, 70, 30);
        changePassword.add(medium, javax.swing.JLayeredPane.DEFAULT_LAYER);

        small.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        small.setText("Short");
        small.setBounds(590, 330, 70, 30);
        changePassword.add(small, javax.swing.JLayeredPane.DEFAULT_LAYER);

        red.setBackground(new java.awt.Color(255, 51, 0));
        red.setOpaque(true);
        red.setBounds(500, 340, 60, 10);
        changePassword.add(red, javax.swing.JLayeredPane.DEFAULT_LAYER);

        blue.setBackground(new java.awt.Color(102, 51, 255));
        blue.setOpaque(true);
        blue.setBounds(480, 340, 80, 10);
        changePassword.add(blue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        green.setBackground(new java.awt.Color(0, 204, 0));
        green.setOpaque(true);
        green.setBounds(460, 340, 100, 10);
        changePassword.add(green, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/changePss.png"))); // NOI18N
        jLabel3.setBounds(0, 0, 1366, 768);
        changePassword.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        image3.setBounds(0, 0, 250, 230);
        jDesktopPane4.add(image3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBounds(800, 200, 250, 230);
        changeAccPic.add(jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton8.setText("Browse");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(860, 450, 130, 40);
        changeAccPic.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/done_d.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/doneg1.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(460, 360, 230, 80);
        changeAccPic.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        userpicChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userpicChange.setBounds(230, 210, 450, 30);
        changeAccPic.add(userpicChange, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/userNameChange.png"))); // NOI18N
        jLabel8.setBounds(0, 0, 1366, 768);
        changeAccPic.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        image.setBounds(0, 0, 220, 200);
        jDesktopPane1.add(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setBounds(820, 140, 220, 200);
        UserAccounts.add(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username.setBounds(230, 170, 450, 30);
        UserAccounts.add(username, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/change_pass.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/glow_pass.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(710, 360, 410, 100);
        UserAccounts.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/change_accpic.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/glow_accpic.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(250, 470, 410, 100);
        UserAccounts.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/delete.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/delete_glow.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(710, 470, 410, 100);
        UserAccounts.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/change_user.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/glow_user.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(250, 360, 410, 100);
        UserAccounts.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/control panel.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 1366, 768);
        UserAccounts.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Temporaly", "Permenantly" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setBounds(560, 160, 300, 40);
        deleteOwnAcc.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Delete Account");
        jLabel10.setBounds(280, 150, 240, 40);
        deleteOwnAcc.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane1.setBounds(370, 240, 620, 260);
        deleteOwnAcc.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/deleteaccount.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/deleteaccountglow.png"))); // NOI18N
        jButton3.setBounds(630, 520, 360, 90);
        deleteOwnAcc.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_controlPanel/homePanel.png"))); // NOI18N
        jLabel9.setBounds(0, 0, 1366, 768);
        deleteOwnAcc.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        deleteOwnAcc.setBounds(0, 0, 1366, 768);
        ControlPanel.add(deleteOwnAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String username = null;
        try {
            DBConnection.setConnection().createStatement().executeUpdate("UPDATE login set username='" + txt_userName.getText() + "' WHERE username='" + accUserName + "'");
            JOptionPane.showMessageDialog(this, "User Name updated succesfully !", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            if (!(txt_userName.getText() == null)) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        deleteOwnAcc.setVisible(true);
        UserAccounts.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        changeUserName.setVisible(true);
        UserAccounts.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        changePassword.setVisible(true);
        UserAccounts.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_confirmPasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmPasKeyReleased
        int getLength = new String(txt_newPas.getPassword()).length();
        if (new String(txt_confirmPas.getPassword()).length() == getLength) {
            if (new String(txt_newPas.getPassword()).equals(new String(txt_confirmPas.getPassword()))) {
                pmatch.setVisible(true);
            } else {
                pdmatch.setVisible(true);
            }
        }
    }//GEN-LAST:event_txt_confirmPasKeyReleased

    private void txt_confirmPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmPasActionPerformed
    }//GEN-LAST:event_txt_confirmPasActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            //------- get the password of the account currently logged in-------
            ResultSet rs = DBConnection.setConnection().createStatement().executeQuery("SELECT * FROM login WHERE username='" + accUserName + "' AND password='" + new String(txt_currPas.getPassword()) + "'");
            if (rs.next()) {

                if (new String(txt_newPas.getPassword()).equals(new String(txt_confirmPas.getPassword()))) {
                    pmatch.setVisible(true);

                    //---------updating new password----------------------------
                    DBConnection.setConnection().createStatement().executeUpdate("UPDATE login set password='" + new String(txt_newPas.getPassword()) + "' WHERE username='" + accUserName + "'");
                    JOptionPane.showMessageDialog(this, "Password changed succesfully", "Information message", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    pdmatch.setVisible(true);
                    setNullAll();
                }

            } else {
                setNullAll();
                txt_currPas.setText(null);
                invalidCurPas.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txt_confirmPasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmPasKeyTyped
    }//GEN-LAST:event_txt_confirmPasKeyTyped

    private void txt_confirmPasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confirmPasKeyPressed
    }//GEN-LAST:event_txt_confirmPasKeyPressed

    private void txt_newPasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_newPasKeyReleased
    }//GEN-LAST:event_txt_newPasKeyReleased

    private void txt_newPasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_newPasKeyPressed
        int getPasNo = new String(txt_newPas.getPassword()).length();
        if (getPasNo <= 3 || !(getPasNo > 4)) {
            small.setVisible(true);
            red.setVisible(true);
            medium.setVisible(false);
            blue.setVisible(false);
        } else if (getPasNo <= 6 || !(getPasNo > 8)) {
            medium.setVisible(true);
            blue.setVisible(true);
            //----------------------
            small.setVisible(false);
            red.setVisible(false);
            strong.setVisible(false);
            green.setVisible(false);
        } else if (getPasNo > 6) {
            strong.setVisible(true);
            green.setVisible(true);
            //----------------------
            small.setVisible(false);
            red.setVisible(false);
            medium.setVisible(false);
            blue.setVisible(false);

        }
    }//GEN-LAST:event_txt_newPasKeyPressed

    private void txt_currPasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_currPasKeyPressed
    }//GEN-LAST:event_txt_currPasKeyPressed

    private void txt_currPasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_currPasKeyReleased
        int getCurPasNo = new String(txt_currPas.getPassword()).length();
        if (getCurPasNo < 1) {
            txt_newPas.setVisible(false);
            txt_confirmPas.setVisible(false);
        } else {
            txt_newPas.setVisible(true);
            txt_confirmPas.setVisible(true);
        }
    }//GEN-LAST:event_txt_currPasKeyReleased

    private void txt_currPasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_currPasKeyTyped
    }//GEN-LAST:event_txt_currPasKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            DBConnection.setConnection().createStatement().executeUpdate("UPDATE usertype set user_picture='" + jpath + "' WHERE user_nic=(SELECT userType_user_nic FROM login WHERE username='" + accUserName + "')");
            JOptionPane.showMessageDialog(this, "User Account picture updated succesfully", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            JFileChooser jf = new JFileChooser();
            jf.showOpenDialog(this);
            File f = jf.getSelectedFile();
            String path = f.getAbsolutePath();
            jpath = path.replace("\\", "/");
            //--------set selected file to desktopPane 
            File ff = new File(path);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(image3.getWidth(), image3.getHeight(), Image.SCALE_SMOOTH);
            image3.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        changeAccPic.setVisible(true);
        userpicChange.setText(accUserName);
        UserAccounts.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem()=="Temporally"){
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new ControlPanel1().setVisible(true);
//                ControlPanel1 cp1 = new ControlPanel1();
//                AWTUtilities.setWindowOpaque(cp1, false);
//                cp1.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ControlPanel;
    private javax.swing.JLayeredPane UserAccounts;
    private javax.swing.JLabel blue;
    private javax.swing.JLayeredPane changeAccPic;
    private javax.swing.JLayeredPane changePassword;
    private javax.swing.JLayeredPane changeUserName;
    private javax.swing.JLayeredPane deleteOwnAcc;
    private javax.swing.JLabel green;
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel invalidCurPas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel medium;
    private javax.swing.JLabel pdmatch;
    private javax.swing.JLabel pmatch;
    private javax.swing.JLabel red;
    private javax.swing.JLabel small;
    private javax.swing.JLabel strong;
    private javax.swing.JPasswordField txt_confirmPas;
    private javax.swing.JPasswordField txt_currPas;
    private javax.swing.JPasswordField txt_newPas;
    private javax.swing.JTextField txt_userName;
    private javax.swing.JLabel username;
    private javax.swing.JLabel userpicChange;
    // End of variables declaration//GEN-END:variables

    public void visibility() {
        //-------------password warnings visibility------------
        pdmatch.setVisible(false);
        pmatch.setVisible(false);
        invalidCurPas.setVisible(false);
        //-------------jlayeredpane visibility-----------------
        changeUserName.setVisible(false);
        changePassword.setVisible(false);
        changeAccPic.setVisible(false);
        deleteOwnAcc.setVisible(false);
        //-------------password strength checking visibility---
        small.setVisible(false);
        medium.setVisible(false);
        strong.setVisible(false);

        red.setVisible(false);
        blue.setVisible(false);
        green.setVisible(false);
    }

    public void setNullAll() {
        txt_confirmPas.setText(null);
        txt_newPas.setText(null);
        txt_userName.setText(null);
    }

    //---------------retriving userPicture----------------------------------
    class A extends javax.swing.JFrame {

        public void getPicture(String n) {
            try {
                ResultSet rs = DBConnection.setConnection().createStatement().executeQuery("SELECT user_picture FROM usertype WHERE user_nic=(SELECT userType_user_nic FROM login WHERE username='" + accUserName + "')");
                if (rs.next()) {
                    BufferedImage bi = ImageIO.read(new File(rs.getString("user_picture")));
                    Image im = bi.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
                    image.setIcon(new ImageIcon(im));
                }
                username.setText(accUserName);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    //----------disable text fields in changing userName-----------------------
    public void disableTextFields() {
        int getCurPasNo = new String(txt_currPas.getPassword()).length();
        if (getCurPasNo < 1) {
            txt_newPas.setVisible(false);
            txt_confirmPas.setVisible(false);
        } else {
            txt_newPas.setVisible(true);
            txt_confirmPas.setVisible(true);
        }
    }

    //----------------methods--------------------------------------------------
    public void methods() {
        visibility();
        disableTextFields();
        A a = new A();
        a.getPicture("a");

    }
    
    //-------------combo box1 @user accounts delete
    
    public void thread(){
        new Thread(new Runnable() {

            @Override
            public void run() {
               
            }
        });
    }
    
    //----------------global variables-----------------------------------------
    String jpath;
    String accUserName;//get the user name currently loged into
}
