/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DBConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SJ slash
 */
public class grn1 extends javax.swing.JFrame {

    /**
     * Creates new form grn1
     */
    public grn1() {
        initComponents();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        combo_item = new javax.swing.JComboBox();
        txt_quantity = new javax.swing.JTextField();
        txt_supplier = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt_balance = new javax.swing.JTextField();
        txt_cashPayed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_grandTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBounds(180, 70, 120, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Item", "Quantity", "price", "Total", "Supplier"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(250, 250, 880, 350);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(330, 620, 100, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(590, 620, 100, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Registe a product");
        jButton3.setBounds(500, 70, 120, 30);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("Register a supplier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(1060, 90, 130, 30);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        combo_item.setEditable(true);
        combo_item.setBounds(250, 130, 220, 30);
        jLayeredPane1.add(combo_item, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt_quantity.setBounds(630, 130, 200, 30);
        jLayeredPane1.add(txt_quantity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt_supplier.setBounds(980, 130, 210, 30);
        jLayeredPane1.add(txt_supplier, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(250, 130, 230, 30);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(1140, 270, 73, 23);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt_balance.setBounds(1020, 190, 190, 40);
        jLayeredPane1.add(txt_balance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt_cashPayed.setBounds(680, 190, 190, 40);
        jLayeredPane1.add(txt_cashPayed, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("jLabel3");
        jLabel3.setBounds(900, 190, 120, 40);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("jLabel3");
        jLabel4.setBounds(560, 190, 120, 40);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txt_grandTotal.setBounds(340, 190, 190, 40);
        jLayeredPane1.add(txt_grandTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("jLabel3");
        jLabel5.setBounds(220, 190, 120, 40);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        timer.setBounds(780, 0, 400, 20);
        jLayeredPane1.add(timer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(1140, 310, 73, 23);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/grn.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 1370, 770);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    }//GEN-LAST:event_jButton4ActionPerformed
    int price;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();
        int i = dt.getRowCount();
        i++;
        v.add(i);
        v.add(combo_item.getSelectedItem());
        v.add(txt_quantity.getText());
        int qu = Integer.parseInt(txt_quantity.getText());
        String id = combo_item.getSelectedItem().toString().split(" ")[0];
        try {
            ResultSet rs = DBConnection.setConnection().createStatement().executeQuery("SELECT pro_unitPrice FROM product WHERE pro_id='" + id + "'");
            while (rs.next()) {
                v.add(rs.getString("pro_unitPrice"));
                price = Integer.parseInt(rs.getString("pro_unitPrice"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        v.add(qu * price);
        //-----------------------------------------------------------------

        double tot = 0;
        for (int a = 0; a < dt.getRowCount(); a++) {
            double d = Double.parseDouble(dt.getValueAt(a, 5).toString());
            tot += d;

        }
        txt_grandTotal.setText(tot + "");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String autoIncremtent = null;
        try {
            DBConnection.setConnection().createStatement().executeUpdate("INSERT INTO grn VALUES('" + autoIncremtent + "','" + txt_cashPayed.getText() + "','" + txt_grandTotal.getText() + "','" + txt_balance.getText() + "','" + timer.getText() + "','" + txt_supplier.getText() + "')");
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            for (int aa = 0; aa < dt.getRowCount(); aa++) {
                String no = dt.getValueAt(aa, 0).toString();
                String pidSplit = dt.getValueAt(aa, 1).toString().split(" ")[0];
                String quantity = dt.getValueAt(aa, 0).toString();
                String price = dt.getValueAt(aa, 0).toString();
                String total = dt.getValueAt(aa, 0).toString();
                String p_id = dt.getValueAt(aa, 0).toString();
                DBConnection.setConnection().createStatement().executeUpdate("INSERT INTO grn_reg VALUES('"+autoIncremtent+"','"+no+"','"+pidSplit+"','"+quantity+"','"+price+"','"+total+"')");
            
                //  stock update
                ResultSet rs=DBConnection.setConnection().createStatement().executeQuery("SELECT pro_quantity FROM stock WHERE product_pro_id='"+pidSplit+"'");
                if(rs.next()){
                    int qu=Integer.parseInt(rs.getString("pro_quantity"));
                    int newQu=Integer.parseInt(txt_quantity.getText());
                    int totQu=qu+newQu;
                    DBConnection.setConnection().createStatement().executeUpdate("UPDATE stock set pro_quantity='"+totQu+"' WHERE product_pro_id='"+pidSplit+"'");
                    JOptionPane.showMessageDialog(this, "Updated succesfully");
                }else{
                    DBConnection.setConnection().createStatement().executeUpdate("INSERT INTO stock VALUES('"+timer.getText()+"','"+quantity+"','"+pidSplit+"')");
                    JOptionPane.showMessageDialog(this, "Addeed succesfully");
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grn1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel timer;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_cashPayed;
    private javax.swing.JTextField txt_grandTotal;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_supplier;
    // End of variables declaration//GEN-END:variables

    public void setTime() {
        Timer t;
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss a");
                timer.setText(sdf.format(d));
            }
        });
        t.start();
    }
}
