/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;
import control.focus;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.invoice_quaries;

/**
 *
 * @author AT
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice1
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_item = new javax.swing.JTextField();
        combo_item = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_qty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_item.setBackground(new java.awt.Color(246, 246, 246));
        txt_item.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_itemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_itemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_itemKeyTyped(evt);
            }
        });
        getContentPane().add(txt_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 180, 30));

        combo_item.setBackground(new java.awt.Color(246, 246, 246));
        combo_item.setEditable(true);
        combo_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_itemMouseClicked(evt);
            }
        });
        combo_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_itemActionPerformed(evt);
            }
        });
        getContentPane().add(combo_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 180, 30));

        jTable1.setBackground(new java.awt.Color(246, 246, 246));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Item ID", "Item", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 780, 400));

        txt_qty.setBackground(new java.awt.Color(246, 246, 246));
        txt_qty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
        });
        getContentPane().add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_itemMouseClicked

    }//GEN-LAST:event_combo_itemMouseClicked

    private void combo_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_itemActionPerformed
        txt_item.setText(combo_item.getSelectedItem().toString());
    }//GEN-LAST:event_combo_itemActionPerformed

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        focus.textFieldsNext(evt, null, combo_item);
        if(evt.getKeyCode() == evt.VK_ENTER){

            try {
                String field1 = txt_item.getText();
                ResultSet rs = invoice_quaries.invoiceTable(field1);
                while(rs.next()){

                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(txt_qty.getText());
                    v.add(rs.getString(4));
                    dt.addRow(v);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_txt_qtyKeyPressed

    private void txt_itemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyPressed
        focus.textFieldsNext(evt, combo_item, null);
    }//GEN-LAST:event_txt_itemKeyPressed

    private void txt_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyReleased
        try {
            String field = txt_item.getText();
            ResultSet rs = invoice_quaries.invoiceSeach(field);
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("pro_name"));
                combo_item.setModel(new DefaultComboBoxModel(v));
                combo_item.setPopupVisible(true);

            }

            if (txt_item.getText().isEmpty()) {
                combo_item.setModel(new DefaultComboBoxModel());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemKeyReleased

    private void txt_itemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Invoice1().setVisible(true);
                Invoice in=new Invoice();
                AWTUtilities.setWindowOpaque(in, false);
                in.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables
}
