/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;
import java.awt.Point;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Queries;
import model.quaries;

/**
 *
 * @author SJ slash
 */
public class userssearch extends javax.swing.JFrame {

    /**
     * Creates new form userssearch
     */
    public userssearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        m = new javax.swing.JScrollPane();
        manger = new javax.swing.JTable();
        s = new javax.swing.JScrollPane();
        supplier = new javax.swing.JTable();
        l = new javax.swing.JScrollPane();
        labours = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtnic = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        manger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nic", "Name", "Gender", "Mobile num", "Home num", "Adress", "position"
            }
        ));
        m.setViewportView(manger);

        m.setBounds(250, 260, 910, 270);
        jLayeredPane1.add(m, javax.swing.JLayeredPane.DEFAULT_LAYER);

        supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nic", "Name", "Gender", "Mobile num", "Company", "Companu Num", "Company Adress"
            }
        ));
        s.setViewportView(supplier);

        s.setBounds(250, 260, 910, 270);
        jLayeredPane1.add(s, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nic", "Name", "Gender", "Mobile num", "Home num", "Adress", "position"
            }
        ));
        l.setViewportView(labours);

        l.setBounds(250, 260, 910, 270);
        jLayeredPane1.add(l, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Managers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(170, 580, 110, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("Update user Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(790, 600, 130, 23);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtnic.setBackground(new java.awt.Color(247, 247, 247));
        txtnic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnicKeyReleased(evt);
            }
        });
        txtnic.setBounds(400, 130, 200, 30);
        jLayeredPane1.add(txtnic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("Suppliers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(170, 550, 110, 23);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("Waiters");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(170, 610, 110, 23);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setBounds(1010, 90, 120, 130);
        jLayeredPane1.add(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1 (2).png"))); // NOI18N
        jLabel1.setBounds(0, 0, 1370, 770);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JComponent[] jcomp = {s, l};
        visibility(jcomp, false);
        m.setVisible(true);
        DefaultTableModel dt = (DefaultTableModel) manger.getModel();
        dt.setRowCount(0);

        try {
            manger.setVisible(true);
            String idnic = txtnic.getText();
            ResultSet rs = quaries.searchusers("usertype");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(8));


                dt.addRow(v);
            }
            String s = dt.getValueAt(manger.getSelectedRow(), 0).toString();
            System.out.println(s);
            ResultSet pic = quaries.searchpic("user", s);
            if (pic.next()) {
                pic.getString("pic");
                System.out.println(pic);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyReleased

        if (txtnic.getCaretPosition() == 9) {
            if (txtnic.getText().lastIndexOf(" v") == -1) {
                txtnic.setText(txtnic.getText() + " v");
            }

        }
    }//GEN-LAST:event_txtnicKeyReleased

    private void txtnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyPressed
        try {
//            quaries.searchusers("users", null, null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtnicKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JComponent[] jcomp = {m, l};
        visibility(jcomp, false);
        s.setVisible(true);

        DefaultTableModel dt = (DefaultTableModel) supplier.getModel();
        dt.setRowCount(0);

        try {
            supplier.setVisible(true);
            String idnic = txtnic.getText();
            ResultSet rs = quaries.searchusers("supplier");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
              
                


                dt.addRow(v);
            }
//           String s=dt.getValueAt(jTable1.getSelectedRow(), 0).toString();
//            System.out.println(s);
//            ResultSet pic=quaries.searchpic("user", "sup_nic");
//            if(pic.next()){
//                pic.getString("pic");
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JComponent[] jcomp = {m, s};
        visibility(jcomp, false);
        l.setVisible(true);
        DefaultTableModel dt = (DefaultTableModel) labours.getModel();

        dt.setRowCount(0);
        try {
            labours.setVisible(true);
            String idnic = txtnic.getText();
            ResultSet rs = quaries.searchusers("labourer");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                 v.add(rs.getString(7));
                  v.add(rs.getString(8));
               


                dt.addRow(v);
            }


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DefaultTableModel dt1 = (DefaultTableModel) labours.getModel();
        DefaultTableModel dt2 = (DefaultTableModel) manger.getModel();
        DefaultTableModel dt3 = (DefaultTableModel) supplier.getModel();

        if (l.isVisible()) {
           waiterAdd add = new waiterAdd("Update");
                AWTUtilities.setWindowOpaque(add, false);
                add.setVisible(true);
//            
            add.txtnic.setText((dt1.getValueAt(labours.getSelectedRow(), 1)).toString());
            add.ttname.setText((dt1.getValueAt(labours.getSelectedRow(), 2)).toString());
            if((dt1.getValueAt(labours.getSelectedRow(), 3)).toString()=="m"){
                add.jbm.setSelected(true);
            }else{
                add.jbf.setSelected(true);
            }
            add.txtmobile.setText((dt1.getValueAt(labours.getSelectedRow(), 4)).toString());
            add.txthome.setText((dt1.getValueAt(labours.getSelectedRow(), 5)).toString());
            add.txtaddress.setText((dt1.getValueAt(labours.getSelectedRow(), 6)).toString());
//            
            add.setVisible(true);
        }
       if (m.isVisible()) {
             addUser add = new addUser("Update");
                AWTUtilities.setWindowOpaque(add, false);
                add.setVisible(true);
               
            add.txtnic.setText((dt2.getValueAt(manger.getSelectedRow(), 0)).toString());
            add.ttname.setText((dt2.getValueAt(manger.getSelectedRow(), 1)).toString());
            if((dt2.getValueAt(manger.getSelectedRow(), 2)).toString()=="m"){
                add.jbm.setSelected(true);
            }else{
                add.jbf.setSelected(true);
            }
            add.txtmobile1.setText((dt2.getValueAt(manger.getSelectedRow(), 3)).toString());
            add.txthome.setText((dt2.getValueAt(manger.getSelectedRow(), 4)).toString());
            add.txtaddress.setText((dt2.getValueAt(manger.getSelectedRow(), 5)).toString());
      
//            
            add.setVisible(true);
        }
       if (s.isVisible()) {
             supplierAdd add = new supplierAdd("Update");
                AWTUtilities.setWindowOpaque(add, false);
                add.setVisible(true);
//            
            add.txtnic.setText((dt3.getValueAt(supplier.getSelectedRow(), 0)).toString());
            add.ttname.setText((dt3.getValueAt(supplier.getSelectedRow(), 1)).toString());
            if((dt3.getValueAt(supplier.getSelectedRow(), 2)).toString()=="m"){
                add.jbm.setSelected(true);
            }else{
                add.jbf.setSelected(true);
            }
            add.txtmobile.setText((dt3.getValueAt(supplier.getSelectedRow(), 3)).toString());
            add.txtcomname.setText((dt3.getValueAt(supplier.getSelectedRow(), 4)).toString());
            add.txtcomcon.setText((dt3.getValueAt(supplier.getSelectedRow(), 5)).toString());
            add.txtcomadd.setText((dt3.getValueAt(supplier.getSelectedRow(), 6)).toString());
//            
            add.setVisible(true);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userssearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userssearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userssearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userssearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userssearch s = new userssearch();
                AWTUtilities.setWindowOpaque(s, false);
                s.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane l;
    private javax.swing.JTable labours;
    private javax.swing.JScrollPane m;
    private javax.swing.JTable manger;
    private javax.swing.JScrollPane s;
    private javax.swing.JTable supplier;
    private javax.swing.JTextField txtnic;
    // End of variables declaration//GEN-END:variables

    public void visibility(JComponent[] c, boolean b) {
        for (JComponent set : c) {
            set.setVisible(b);
        }
    }
}
