/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;
import control.DBConnection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Queries;
import model.quaries;

/**
 *
 * @author Naveen
 */
public class waiterAdd extends javax.swing.JFrame {

    String status;
    String waiterId;

    /**
     * Creates new form waiterAdd
     */
    public waiterAdd(String getPath) {
        status = JOptionPane.showInputDialog(null, "Enter Status :");
        initComponents();
             if (getPath == "Save") {
            sbtn.setVisible(true);
            ubtn.setVisible(false);
        }
        if (getPath == "Update") {
            ubtn.setVisible(true);
            sbtn.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtnic = new javax.swing.JTextField();
        ttname = new javax.swing.JTextField();
        jbf = new javax.swing.JRadioButton();
        jbm = new javax.swing.JRadioButton();
        txtmobile = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        sbtn = new javax.swing.JButton();
        txthome = new javax.swing.JTextField();
        ubtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txtnic.setBackground(new java.awt.Color(247, 247, 247));
        txtnic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnicKeyTyped(evt);
            }
        });
        txtnic.setBounds(360, 170, 330, 30);
        jLayeredPane1.add(txtnic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ttname.setBackground(new java.awt.Color(247, 247, 247));
        ttname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ttname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ttnameKeyTyped(evt);
            }
        });
        ttname.setBounds(360, 210, 340, 30);
        jLayeredPane1.add(ttname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbf.setBackground(new java.awt.Color(247, 247, 247));
        jbf.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbf.setForeground(new java.awt.Color(0, 177, 255));
        jbf.setText("Female");
        jbf.setBounds(470, 260, 69, 25);
        jLayeredPane1.add(jbf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbm.setBackground(new java.awt.Color(247, 247, 247));
        jbm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbm.setForeground(new java.awt.Color(0, 177, 255));
        jbm.setText("Male");
        jbm.setBounds(370, 260, 55, 25);
        jLayeredPane1.add(jbm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtmobile.setBackground(new java.awt.Color(247, 247, 247));
        txtmobile.setText("+94");
        txtmobile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmobileKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmobileKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobileKeyTyped(evt);
            }
        });
        txtmobile.setBounds(360, 350, 340, 30);
        jLayeredPane1.add(txtmobile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtaddress.setBackground(new java.awt.Color(247, 247, 247));
        txtaddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtaddress.setBounds(360, 430, 340, 30);
        jLayeredPane1.add(txtaddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sbtn.setText("Save");
        sbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnActionPerformed(evt);
            }
        });
        sbtn.setBounds(780, 570, 57, 23);
        jLayeredPane1.add(sbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txthome.setBackground(new java.awt.Color(247, 247, 247));
        txthome.setText("+94");
        txthome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txthome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthomeKeyTyped(evt);
            }
        });
        txthome.setBounds(360, 390, 170, 30);
        jLayeredPane1.add(txthome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ubtn.setText("Update");
        ubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubtnActionPerformed(evt);
            }
        });
        ubtn.setBounds(850, 570, 67, 23);
        jLayeredPane1.add(ubtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/waiteradd..png"))); // NOI18N
        jLabel1.setBounds(10, 0, 1366, 768);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if(txtnic.getText().length()>10){
            evt.consume();
        }
    }//GEN-LAST:event_txtnicKeyTyped

    private void txtnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyReleased

        if (txtnic.getCaretPosition() == 9) {
            if (txtnic.getText().lastIndexOf(" v") == -1) {
                txtnic.setText(txtnic.getText() + " v");
            }
            if (Integer.parseInt(txtnic.getText().substring(2, 5)) > 500) {
                //                if (Integer.parseInt(txtnic.getText().substring(0, 2)) + 1900 > new DateTime().getYear() - 23) {
                jbf.setSelected(true);
                //                }

            } else {
                jbm.setSelected(true);
            }
            if (ttname.getText().isEmpty()) {
            } else {
                if (Character.isLowerCase(ttname.getText().charAt(0))) {
                    ttname.setText(new String(String.valueOf(ttname.getText().charAt(0))).toUpperCase() + ttname.getText().substring(1));
                }
            }
        }
    }//GEN-LAST:event_txtnicKeyReleased

    private void ttnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttnameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) | c == ' ')) {
            evt.consume();

        }
        if (ttname.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_ttnameKeyTyped

    private void txtmobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileKeyPressed
        // TODO add your handling code here:

        if (txtmobile.getCaretPosition() <= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtmobileKeyPressed

    private void txtmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) | c == '+')) {
            evt.consume();
        }
        if (txtmobile.getText().length() == 12) {
            evt.consume();
        }

        if (txtmobile.getCaretPosition() == 3) {
            if (evt.getKeyChar() == '0') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtmobileKeyTyped

    private void txtmobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileKeyReleased
    }//GEN-LAST:event_txtmobileKeyReleased
    String m = "";
    private void sbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnActionPerformed

        setId();
        System.out.println(waiterId);
        try {

            if (jbm.isSelected()) {
                m = "m";
            } else if (jbf.isSelected()) {
                m = "f";

            }
            String[] name = ttname.getText().split(" ");
            final String feild[] = {waiterId, txtnic.getText(), ttname.getText(), m, txtmobile.getText(), txthome.getText(), txtaddress.getText(), status};
            quaries.waitersave("labourer", feild);

            //        String[] ar={"123"z,"123","123","123","123","123","123","123","123","123","123"};
            //        quaries.autosave("usertype", ar);
        } catch (Exception e) {
            e.printStackTrace();
        }
        clear();
    }//GEN-LAST:event_sbtnActionPerformed

    private void txthomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthomeKeyPressed
        // TODO add your handling code here:

        if (txthome.getCaretPosition() <= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txthomeKeyPressed

    private void txthomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthomeKeyReleased
    }//GEN-LAST:event_txthomeKeyReleased

    private void txthomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthomeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) | c == '+')) {
            evt.consume();
        }
        if (txthome.getText().length() == 12) {
            evt.consume();
        }

        if (txthome.getCaretPosition() == 3) {

            if (evt.getKeyChar() == '0') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txthomeKeyTyped

    private void ubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubtnActionPerformed
         try {
            String name[]={"lab_name","lab_gender","lab_mobileNumber","lab_homeNumber","lab_address"};
            String column[]={ttname.getText(),m,txtmobile.getText(),txthome.getText(),txtaddress.getText()};
            
            quaries.update("labourer", name, column, txtnic.getText(), "lab_nic");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ubtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(waiterAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(waiterAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(waiterAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(waiterAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                waiterAdd s = new waiterAdd("Save");
                AWTUtilities.setWindowOpaque(s, false);
                s.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JRadioButton jbf;
    public javax.swing.JRadioButton jbm;
    private javax.swing.JButton sbtn;
    public javax.swing.JTextField ttname;
    public javax.swing.JTextField txtaddress;
    public javax.swing.JTextField txthome;
    public javax.swing.JTextField txtmobile;
    public javax.swing.JTextField txtnic;
    private javax.swing.JButton ubtn;
    // End of variables declaration//GEN-END:variables

    public void setId() {
        try {
            ResultSet rs = DBConnection.setConnection().createStatement().executeQuery("SELECT * FROM labourer ORDER BY CAST(lab_id AS SIGNED INTEGER) ASC");
            if (rs.next()) {
                rs.last();
                waiterId = Integer.parseInt(rs.getString(1)) + 1 + "";
            } else {
                waiterId = 1 + "";
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void clear() {
         JTextField[] tf={txtnic, ttname, txtmobile, txthome, txtaddress};
                 for(int val=0;val<tf.length;val++){
                     tf[val].setText(null);
                 }
    }
}
